#!/bin/bash
# input from fb.pl
# output augments fb.pl
temp=_temp_${RANDOM}
temp2=_temp_${RANDOM}
layer=layer_${RANDOM}

swipl -q \
      -g "consult(common)." \
      -g "consult(layer2)." \
      -g "common." \
      -g "layer2." \
      -g "halt." \
      > $temp
cat fb.pl $temp >$temp2
mv $temp2 fb.pl
rm -f $temp
rm -f $layer.pl
