#!/bin/bash
# input from fb.pl
# output augments fb.pl
temp=temp_${RANDOM}
temp2=temp_${RANDOM}
swipl -q \
      -g 'consult(common).' \
      -g 'consult(layer1).' \
      -g 'common.' \
      -g 'makeLayer1.' \
      -g 'halt.' \
      > $temp
cat fb.pl $temp >$temp2
mv $temp2 fb.pl
rm $temp
